#!/usr/bin/env bash

# CLI
brew install bash
brew install zsh
brew install git

# htop
brew install htop
chmod 6555 /usr/local/bin/htop
sudo chown root /usr/local/bin/htop

# Apps
brew cask install sublime-text
brew cask install alfred
brew cask install spotify
brew cask install slack
brew cask install vlc
brew cask install whatsapp
brew cask install dropbox
brew cask install skype
brew cask install google-chrome
brew cask install transmission
brew cask install bartender
brew cask install cleanmymac
brew cask install istat-menus
brew cask install little-snitch

echo 'Manually install edu.blancas: Dash 3, Airmail 3, Tweetbot, Fantastical'
echo 'Manually install fam.blancas: Divvy, Codebox'


# brew cask install mactex
#fantastical
#iterm
#typora/mou
#things

# Import settings
# Alfred
# Divvy
# sublime text


# Setup Sublime Text
echo 'Install Package Control ST'

# Dev folder
mkdir ~/dev
cd ~/dev
git clone https://github.com/edublancas/dotfiles
cd dotfiles
