#!/usr/bin/env python
"""
Create symlinks to $HOME
"""
import os
import glob

DOTS = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
HOME = os.path.expanduser('~')


def make_dot_path(source):
    """Build the dotfile destination from the original path
    """
    filename = os.path.basename(source).replace('.symlink', '')
    return os.path.join(HOME, '.'+filename)


sources = glob.glob(os.path.join(DOTS, '**/*.symlink'), recursive=True)
destinations = [make_dot_path(s) for s in sources]

for source, destination in zip(sources, destinations):

    if os.path.isfile(destination):
        print(f'{destination} exists, removing...')
        os.remove(destination)

    print(f'Symlink created: {destination} -> {source}\n')
    os.symlink(source, destination)


print('Done creating symlinks...')
